/* Metadados dos artigos do blog "Para compreender".
   O corpo de cada artigo fica em src/pages/artigos/<file>.html */

export const ARTICLES = [
  {
    slug: 'quando-os-vinculos-revelam-mais-sobre-nos-do-que-imaginamos',
    file: 'relacionamentos',
    category: 'Relacionamentos',
    readingTime: '6 min de leitura',
    title: 'Quando os vínculos revelam mais sobre nós do que imaginamos',
    seoTitle: 'Quando os vínculos revelam mais sobre nós do que imaginamos | Veruska Martins',
    description: 'Os relacionamentos não revelam apenas quem amamos, mas também nossos medos, expectativas e padrões emocionais. Descubra como os vínculos podem se tornar um caminho para o autoconhecimento.',
    summary: 'Os relacionamentos dizem muito sobre quem está ao nosso lado, mas revelam ainda mais sobre nós mesmos. Um convite a refletir sobre como seus vínculos podem iluminar medos, expectativas e padrões invisíveis, tornando-se um caminho valioso para o autoconhecimento.',
    quote: 'Os relacionamentos não revelam apenas quem escolhemos amar. Revelam quem acreditamos precisar ser para merecer amor.',
  },
  {
    slug: 'quando-a-mente-nao-encontra-descanso',
    file: 'ansiedade',
    category: 'Ansiedade',
    readingTime: '8 min de leitura',
    title: 'Quando a mente não encontra descanso',
    seoTitle: 'Quando a mente não encontra descanso: compreendendo a ansiedade | Veruska Martins',
    description: 'A ansiedade nem sempre faz barulho. Descubra por que a mente não encontra descanso e como compreender esse processo pode ser o primeiro passo para um olhar mais gentil sobre si mesmo.',
    summary: 'A ansiedade nem sempre faz barulho. Às vezes ela se esconde em pensamentos que não descansam e na sensação de que é preciso estar sempre um passo à frente. Um convite para compreender o que a mente tenta proteger quando não encontra paz.',
    quote: 'Talvez a paz não seja o silêncio absoluto da mente. Talvez seja a possibilidade de continuar caminhando, mesmo quando alguns pensamentos insistem em fazer barulho.',
  },
  {
    slug: 'luto-quando-precisamos-aprender-a-viver-apos-uma-perda',
    file: 'luto',
    category: 'Luto',
    readingTime: '7 min de leitura',
    title: 'Quando precisamos aprender a viver após uma perda',
    seoTitle: 'Quando precisamos aprender a viver após uma perda | Reflexões sobre o luto — Veruska Martins',
    description: 'Aprender a viver após uma perda não significa esquecer quem partiu. Uma reflexão acolhedora sobre o luto, a saudade e a reconstrução da vida.',
    summary: 'Aprender a viver após uma perda não significa esquecer quem partiu, mas descobrir uma nova forma de seguir em frente. Um convite para compreender o luto sem pressa, acolher a saudade e reconhecer que seguir vivendo também pode ser uma forma de amar.',
    quote: 'Seguir em frente não é deixar quem partiu para trás. É aprender que o amor pode continuar existindo mesmo quando a presença já não é possível.',
  },
  {
    slug: 'quando-ate-existir-parece-exigir-esforco',
    file: 'depressao',
    category: 'Depressão',
    readingTime: '9 min de leitura',
    title: 'Quando até existir parece exigir esforço',
    seoTitle: 'Quando até existir parece exigir esforço: compreendendo a depressão | Veruska Martins',
    description: 'A depressão nem sempre se manifesta como tristeza. Como reconhecer seus sinais, compreender o sofrimento invisível e encontrar caminhos para o acolhimento e o cuidado.',
    summary: 'A depressão nem sempre se parece com tristeza. Muitas vezes surge como um cansaço profundo, que torna até as tarefas mais simples um desafio. Uma reflexão sobre o peso invisível da depressão e a importância do acolhimento como caminho para reencontrar sentido.',
    quote: 'A depressão não é apenas tristeza. Muitas vezes, ela se manifesta como um esgotamento tão profundo que até existir parece exigir esforço.',
  },
  {
    slug: 'quando-o-olhar-do-outro-passa-a-definir-o-seu-valor',
    file: 'autoestima',
    category: 'Autoestima',
    readingTime: '12 min de leitura',
    title: 'Quando o olhar do outro passa a definir o seu valor',
    seoTitle: 'Quando o olhar do outro passa a definir o seu valor | Veruska Martins',
    description: 'Por que a necessidade constante de aprovação pode enfraquecer sua autoestima e como construir um senso de valor que não dependa do olhar dos outros.',
    summary: 'Passamos boa parte da vida tentando corresponder às expectativas de quem amamos, admiramos ou tememos decepcionar. Mas o que acontece quando nossa autoestima passa a depender da aprovação dos outros? Um convite a recuperar um olhar mais gentil para si mesmo.',
    quote: 'O problema não é desejar ser visto. O sofrimento começa quando acreditamos que só existimos através do olhar de alguém.',
  },
  {
    slug: 'quando-reencontrar-quem-voce-e-se-torna-o-caminho-mais-importante',
    file: 'reconstrucao',
    category: 'Reconstrução de si',
    readingTime: '8 min de leitura',
    title: 'Quando reencontrar quem você é se torna o caminho mais importante',
    seoTitle: 'Quando reencontrar quem você é se torna o caminho mais importante | Veruska Martins',
    description: 'Há momentos em que nos afastamos de quem realmente somos. Como o autoconhecimento e a reconstrução de si podem ajudar a criar uma vida mais autêntica e significativa.',
    summary: 'Em determinados momentos da vida, percebemos que nos adaptamos tanto às expectativas dos outros que deixamos de reconhecer nossos próprios desejos. Uma reflexão sobre identidade, autenticidade e o delicado processo de reconstrução de si.',
    quote: 'Há um momento em que percebemos que não estamos perdidos no mundo. Estamos apenas distantes de nós mesmos. E talvez o caminho de volta seja a viagem mais importante da vida.',
  },
];
